name: test

on:
  pull_request:
  push:
    paths-ignore:
      - '**.md'

env:
  CI: true

jobs:
  skip_duplicate_runs:
    runs-on: ubuntu-latest
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@ea548f2a2a08c55dcb111418ca62181f7887e297
        with:
          concurrent_skipping: 'same_content'
          paths_ignore: '["**/*.md"]'

  test:
    needs: skip_duplicate_runs
    if: ${{ needs.skip_duplicate_runs.outputs.should_skip != 'true' }}
    name: 'node v${{ matrix.node-version }} on ${{ matrix.os }}'
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: ['ubuntu-latest', 'macos-latest', 'windows-latest']
        node-version: [10, 12, 14]

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: set up node v${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: install
        run: yarn install --prefer-offline

      - name: test
        run: yarn test
